export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER__FAILURE';

export const INIT_GLOBAL_GUIDE = 'INIT_GLOBAL_GUIDE';
export const INIT_GLOBAL_GUIDE_SUCCESS = 'INIT_GLOBAL_GUIDE_SUCCESS';

export const INIT_SCORE_RANK = 'INIT_SCORE_RANK';
export const INIT_SCORE_RANK_SUCCESS = 'INIT_SCORE_RANK_SUCCESS';

export const INIT_CLASS_REPORT = 'INIT_CLASS_REPORT';
export const INIT_CLASS_REPORT_SUCCESS = 'INIT_CLASS_REPORT_SUCCESS';


export const INIT_LEVEL_REPORT = 'INIT_LEVEL_REPORT';
export const INIT_LEVEL_REPORT_SUCCESS = 'INIT_LEVEL_REPORT_SUCCESS';

export const INIT_SUBJECT_REPORT = 'INIT_SUBJECT_REPORT';
export const INIT_SUBJECT_REPORT_SUCCESS = 'INIT_SUBJECT_REPORT_SUCCESS';

export const SOME_EXAM_TOTAL_ONE = 'SOME_EXAM_TOTAL_ONE';
export const SOME_EXAM_TOTAL_TWO = 'SOME_EXAM_TOTAL_TWO';
export const SOME_EXAM_TOTAL_THREE = 'SOME_EXAM_TOTAL_THREE';

export const SOME_EXAM_ANALYSIS_ONE = 'SOME_EXAM_ANALYSIS_ONE';
export const SOME_EXAM_ANALYSIS_TWO = 'SOME_EXAM_ANALYSIS_TWO';
export const SOME_EXAM_ANALYSIS_THREE = 'SOME_EXAM_ANALYSIS_THREE';
